alias rn="nice -n 5 npx react-native"
alias rni="nice -n 5 npx react-native run-ios"
alias rnr="nice -n 5 npx react-native run-android"
alias rna="rnr"
alias rnpkg="nice -n 5 ./node_modules/react-native/packager/launchPackager.command ; exit;"
